// LED status updates
//
// Copyright (C) 2021 Eric Callahan <arksine.code@gmail.com>
//
// This file may be distributed under the terms of the GNU GPLv3 license.

#include "autoconf.h" // CONFIG_ENABLE_LED
#include "board/gpio.h" // gpio_out_setup
#include "board/misc.h" // timer_read_time
#include "ctr.h" // DECL_CTR
#include "flashcmd.h" // flashcmd_is_in_transfer
#include "sched.h" // DECL_INIT

#define WAIT_BLINK_TIME     1000000
#define XFER_BLINK_TIME     20000
#define IDENTIFY_BLINK_TIME 166667   // ~167ms for 3 blinks/sec
#define IDENTIFY_DURATION   10000000 // 10 seconds

DECL_CTR("DECL_LED_PIN " __stringify(CONFIG_STATUS_LED_PIN));
extern uint32_t led_gpio, led_gpio_high; // Generated by buildcommands.py

static struct gpio_out led;
static uint32_t last_blink_time;
static uint32_t identify_end_time;
static uint8_t identify_active;

void
led_init(void)
{
    led = gpio_out_setup(led_gpio, led_gpio_high);
    last_blink_time = timer_read_time();
}
DECL_INIT(led_init);

void
led_blink_task(void)
{
    uint32_t curtime = timer_read_time();

    // Check if identify mode expired
    if (identify_active && timer_is_before(identify_end_time, curtime))
        identify_active = 0;

    // Determine blink rate
    uint32_t usec;
    if (identify_active)
        usec = IDENTIFY_BLINK_TIME;
    else if (flashcmd_is_in_transfer())
        usec = XFER_BLINK_TIME;
    else
        usec = WAIT_BLINK_TIME;

    uint32_t endtime = last_blink_time + timer_from_us(usec);
    if (timer_is_before(endtime, curtime)) {
        gpio_out_toggle(led);
        last_blink_time = timer_read_time();
    }
}
DECL_TASK(led_blink_task);

void
led_identify(void)
{
    identify_end_time = timer_read_time() + timer_from_us(IDENTIFY_DURATION);
    identify_active = 1;
}

int
led_is_enabled(void)
{
    return CONFIG_ENABLE_LED;
}
